# Generated by Django 3.1.1 on 2020-09-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tds_amount',
        ),
        migrations.AddField(
            model_name='item',
            name='tds_rate',
            field=models.FloatField(help_text='(%)', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='gst_rate',
            field=models.FloatField(help_text='(%)'),
        ),
    ]
